apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbtflight-app
  labels:
    app: kbtflight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kbtflight
  template:
    metadata:
      labels:
        app: kbtflight
    spec:
      containers:
        - name: kbtflight-app
          image: kbtflights-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "${SPRING_DATASOURCE_URL}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "${SPRING_DATASOURCE_USERNAME}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: kbtflight-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: kbtflight
  type: LoadBalancer



      