apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbtflight-app
  labels:
    app: kbtflight
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kbtflight
  template:
    metadata:
      labels:
        app: kbtflight
    spec:
      containers:
        - name: kbtflight-app
          image: kbtflight-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/kubernetesFL"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: kbtflight-service
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: kbtflight
  type: LoadBalancer



      